path: /home/uxin/yolo/original/pose/derived/bbat5-v1/pose
train: /home/uxin/yolo/original/pose/derived/bbat5-v1/pose/splits/search-train.txt
val: /home/uxin/yolo/original/pose/derived/bbat5-v1/pose/splits/search-val.txt
names:
  0: ball
  1: bat
kpt_shape:
- 2
- 3
flip_idx:
- 0
- 1
