data: configs/coco2017.yaml
batch: 16
imgsz: 640
device: "0"
workers: 8
seed: 0
amp: true
deterministic: true
optimizer: MuSGD
nbs: 16
end2end: true
warmup_momentum: 0.8
warmup_bias_lr: 0.0
close_mosaic: 10
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
bgr: 0.0
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
