path: /home/uxin/yolo/original/pose/derived/bbat5-v1/detect
train: /home/uxin/yolo/original/pose/derived/bbat5-v1/detect/splits/search-train.txt
val: /home/uxin/yolo/original/pose/derived/bbat5-v1/detect/splits/search-val.txt
names:
  0: ball
  1: bat
